version: '3.7'
services:
  bd_pst:
    image: postgres:12
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5443:5432'
    volumes:
      - ~/bd:/var/lib/postgresql/data

  nextjs_app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - bd_pst
    environment:
      - NODE_ENV=production
      - JWT_SECRET_KEY=your_secret_key
      - DATABASE_URL=postgresql://postgres:postgres@bd_pst:5432/postgres
